format = '\[$username@$hostname $os $directory$dotnet$kubernetes\]$line_break$character'

[username]
style_user = "yellow"
style_root = "red bold"
format = "[$user]($style)"
disabled = false
show_always = true

[hostname]
disabled = false
ssh_only = false
format = "[$hostname](blue)"

[os]
disabled = false
style = "fg:green"
format = "[$symbol]($style) "

[os.symbols]
Windows = ""
Ubuntu = "󰕈"
Macos = "󰀵"
Linux = "󰌽"

[directory]
style = "cyan bold"
truncation_length = 5
truncation_symbol = "…/"
home_symbol = "~"
truncate_to_repo = false

[character]
disabled = false
success_symbol = "[>_](green)"
error_symbol = "[>_](red)"

[dotnet]
disabled = false
format = '\([$symbol($version )($tfm )]($style)\)'

[kubernetes]
disabled = false
symbol = ""
# symbol = "⎈"
format = '\([$symbol](blue) |[$context](red):[$namespace](cyan)\)'

[line_break]
disabled = false
